[package]
name = "rust-wasm-poc"
version = "0.1.0"
authors = ["aimeelynnramirez"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.51"


[lib]
crate-type = ["cdylib", "rlib"]
